services:
  db:
    container_name: lucra-be-take-home_db
    image: postgres:16.4
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: local
volumes:
  db_data:
